### ISSUE TITLE
Invalid task order in merge

### ISSUE THREAD

**Issue by prekucki** [golemfactory/gwasm-runner#18]
test 

`gwasm-runner -b Golem target/wasm32-unknown-emscripten/release/mandelbrot.wasm 1000 1000 5`

**Result**

![out](https://user-images.githubusercontent.com/56750/66929836-01c27e80-f034-11e9-80d7-9b459e332561.png)

**On local**

`gwasm-runner -vv -b local target/wasm32-unknown-emscripten/release/mandelbrot.wasm 1000 1000 5`

![out](https://user-images.githubusercontent.com/56750/66930028-4817dd80-f034-11e9-9441-bd77a82f60be.png)

**Comment by kmazurek** [comment]
Subtask results are merged based on the ordering in `merge/tasks_output.json` file. In the case of the local runner, this ordering is deterministic (the same as in input). However, in Brass runner output paths are written in the order subtasks are completed. Since they are computed in parallel the output order is non-deterministic.
The simplest fix I see here is to have the output follow the input's ordering, I will update the Brass runner. @prekucki can you confirm whether GU backend is affected by this as well?

**Comment by prekucki** [comment]
gu backend creates tasks in output json in order. only brass have this bug.
